name: Build & test

on:
  push:
    branches:
      - devel
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      C_COMPILER: clang
      CXX_COMPILER: clang++
      BUILD_TYPE: Debug
      CXX_STANDARD: "17"

    name: "No XSimd"
    
    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@v3
    - uses: seanmiddleditch/gha-setup-vsdevenv@master

    - name: Install conan
      shell: bash
      env:
        CC: "${{ env.C_COMPILER }}"
        CXX: "${{ env.CXX_COMPILER }}"
      run: |
        pip install conan==2.0.7
        conan profile detect --name ci --force
        python $GITHUB_WORKSPACE/support/update-conan-profile.py $(conan profile path ci) ${{env.BUILD_TYPE}} ${{env.C_COMPILER}} ${{env.CXX_COMPILER}} ${{env.CXX_STANDARD}}

    - name: Cache conan packages
      id: cache-conan
      uses: actions/cache@v3
      with:
        path: ~/.conan2/p
        key: conan-cache-packages-ubuntu-latest-${{ env.C_COMPILER }}-${{ env.BUILD_TYPE }}-${{ env.CXX_STANDARD }}

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      env:
        CC: ${{env.C_COMPILER}}
        CXX: ${{env.CXX_COMPILER}}
      run: |
        conan install $GITHUB_WORKSPACE --output-folder=. --build=missing -pr ci -pr:b ci -s build_type=${{ env.BUILD_TYPE }}
        conan cache clean
        cmake $GITHUB_WORKSPACE --preset conan-debug -DMATHTER_USE_XSIMD:BOOL=OFF

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ./Bin/UnitTest
